### ISSUE TITLE
Gurobi Alternative?

### ISSUE THREAD

**Issue by DahliaWitt** [Staffjoy/mobius-assignment#1]
I am highly enjoying using Staffjoy, but is there an alternative for using Gurobi in mobius? If my understanding is correct, a license is about $14,000 for Gurobi, which is way too much for the small project I am working on. Is there an alternative that can be switched in?

**Comment by philipithomas** [comment]
**Short answer:** This uses the Gurobi Python library, so an alternative would have to be a ground-up rewrite. There is no simple alternative.

**Long answer:** We originally didn't use Gurobi. We used the CBC open-source solver. The original implementation was a different codebase, written in Julia, which is open-sourced (but no longer compatible with the Suite API): https://github.com/Staffjoy/autoscheduler. It used the JuliaOpt library, which lets you swap different solvers into models. We ran into speed issues with CBC, so we swapped it out with Gurobi. When we had to make some major changes, we rewrote it into Python using their official library. 

Since this transition, I have learned a lot more about tuning CBC models. I think it's *possible* to rewrite the mobius repo into using CBC, including reasonable solve times. However, this would require (1) porting this model to Julia/JuliaOpt, then (2) spending time tuning the CBC parameters. (Even then, CBC might be slow, or additional time would need to be spent in creating heuristics to speed up the model. The way employee preferences work might need to be changed or dropped, too.).

I think this would take me about a week of work to test as a proof of concept.  However, I don't know if anybody would actually use that rewrite, and I personally would not use it. So, I'd be interested in attempting this as a contract project (which would cost less in labor than a Gurobi license) if any companies would benefit.
